SELECT * FROM AGENTS;
CREATE PROCEDURE SLET_AGENT @WORKING_AREA CHAR(35)
AS
SELECT * FROM AGENTS WHERE WORKING_AREA=@Working_AREA;
Go

EXEC SLET_AGENT @WORKING_AREA= 'Bangalore';

SELECT *FROM AGENTS
WHERE WORKING_AREA ='Bangalore';