SELECT *FROM AGENTS;
CREATE PROCEDURE LONDON_QUERY @AREA char(15), @COM FLOAT(10)
AS
SELECT *FROM AGENTS
WHERE WORKING_AREA=@AREA AND COMMISSION = @COM;
GO
EXEC LONDON_QUERY @AREA='London',@COM='0.15';
EXEC LONDON_QUERY @AREA='chennai' , @COM='0.14';
EXEC LONDON_QUERY @AREA='Bangalore' , @COM='0.14';